name: photos_library
description: A simple plugin to demo how to interact with iOS PhotosKit API
version: 0.0.1
author: Yang Hongbo
homepage: https://github.com/sprhawk/flutter_photos_library

dependencies:
  flutter:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    pluginClass: PhotosLibraryPlugin
